# Generated by Django 4.1.7 on 2023-04-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Sector",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Poliklinika nomi"),
                ),
            ],
            options={
                "verbose_name": "Poliklinika",
                "verbose_name_plural": "Poliklinikalar",
            },
        ),
    ]
