# Generated by Django 4.1.7 on 2023-04-01 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "urer_type",
                    models.CharField(
                        choices=[("sector_leader", "Sektor bosh shifokori")],
                        default="Ishtixon tumani 1-sonli poliklinika",
                        max_length=255,
                        verbose_name="Fuqorolar turi",
                    ),
                ),
            ],
        ),
    ]
