# Generated by Django 4.1.7 on 2023-04-02 04:26

import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("MAHALLA", "0002_alter_user_options_rename_urer_type_user_user_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "Shifokor", "verbose_name_plural": "Shifokorlar"},
        ),
        migrations.AddField(
            model_name="user",
            name="discription",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="MAHALLA/images/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="short_discription",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="name",
            field=models.CharField(max_length=25, verbose_name="F.I.O"),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("sector_leader", "Sektor bosh shifokori"),
                    ("add_leader", "Bosh shifokori"),
                    ("app_leader", "Hamshira"),
                ],
                default="Ishtixon tumani 1-sonli poliklinika",
                max_length=255,
                verbose_name="Shiforkorlar lavozimi",
            ),
        ),
    ]
