# Generated by Django 4.1.7 on 2023-04-01 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0002_alter_sector_name_citizin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="citizin",
            name="sector",
            field=models.ForeignKey(
                help_text="Poliklinika qaysi sektorga tegishli ekanligini tanlang",
                on_delete=django.db.models.deletion.PROTECT,
                to="mahalla.sector",
            ),
        ),
    ]
