# Generated by Django 4.1.7 on 2023-04-01 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0003_alter_citizin_sector"),
    ]

    operations = [
        migrations.CreateModel(
            name="Hosptal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Poliklinika nomi"),
                ),
            ],
            options={
                "verbose_name": "Poliklinika",
                "verbose_name_plural": "Poliklinikalar",
            },
        ),
        migrations.AlterModelOptions(
            name="sector",
            options={"verbose_name": "Sektor", "verbose_name_plural": "Sektorlar"},
        ),
        migrations.DeleteModel(
            name="Citizin",
        ),
        migrations.AddField(
            model_name="hosptal",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                help_text="Poliklinika qaysi sektorga tegishli ekanligini tanlang",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="mahalla.sector",
            ),
        ),
    ]
