# Generated by Django 4.1.7 on 2023-04-02 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MAHALLA", "0003_alter_user_options_user_discription_user_photo_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="discription",
        ),
        migrations.RemoveField(
            model_name="user",
            name="photo",
        ),
        migrations.RemoveField(
            model_name="user",
            name="short_discription",
        ),
    ]
