# Generated by Django 4.1.7 on 2023-04-02 04:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("MAHALLA", "0004_remove_user_discription_remove_user_photo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default=django.utils.timezone.now, upload_to="MAHALLA/images/"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="short_discription",
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
