# Generated by Django 4.1.7 on 2023-04-02 04:36

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0005_remove_hosptal_name_remove_hosptal_sector"),
    ]

    operations = [
        migrations.AddField(
            model_name="hosptal",
            name="name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="Poliklinika nomi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hosptal",
            name="sector",
            field=models.ForeignKey(
                blank=True,
                help_text="Poliklinika qaysi sektorga tegishli ekanligini tanlang",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="mahalla.sector",
            ),
        ),
    ]
