# Generated by Django 4.1.7 on 2023-04-02 04:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("MAHALLA", "0005_user_photo_user_short_discription"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="discription",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
