# Generated by Django 4.1.7 on 2023-04-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MAHALLA", "0006_user_discription"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("sector_leader", "Sektor bosh shifokori"),
                    ("add_leader", "Bosh shifokori"),
                    ("app_leader", "Hamshira"),
                ],
                default="Ishtixon tumani 1-sonli poliklinika",
                help_text="Shifokor lavozimini kiriting",
                max_length=255,
                verbose_name="Shiforkorlar lavozimi",
            ),
        ),
    ]
