# Generated by Django 4.1.7 on 2023-04-02 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0009_sector_show_view"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sector",
            name="show_view",
        ),
    ]
