# Generated by Django 4.1.7 on 2023-04-02 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0010_remove_sector_show_view"),
    ]

    operations = [
        migrations.AddField(
            model_name="hosptal",
            name="gender",
            field=models.CharField(
                choices=[("man", "Erkak"), ("woman", "Ayol")],
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="Shifokor jinsi",
            ),
            preserve_default=False,
        ),
    ]
