# Generated by Django 4.1.7 on 2023-04-02 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0011_hosptal_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sector",
            name="name",
        ),
        migrations.AlterField(
            model_name="hosptal",
            name="gender",
            field=models.CharField(
                choices=[("man", "Ha"), ("woman", "Yo'q")],
                help_text="Ilg'or poliklinikami yo'qmi",
                max_length=255,
                verbose_name="Yetakchi poliklinikami",
            ),
        ),
    ]
