# Generated by Django 4.1.7 on 2023-04-02 07:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0012_remove_sector_name_alter_hosptal_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="name",
            field=models.CharField(
                default=django.utils.timezone.now,
                max_length=255,
                verbose_name="Sektor nomi",
            ),
            preserve_default=False,
        ),
    ]
