# Generated by Django 4.1.7 on 2023-04-02 16:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0013_sector_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sector",
            name="add",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Ushbu sektor qaysi viloyatga tegishli ekanligini belgilang",
                max_length=255,
                verbose_name="Viloyat nomi",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sector",
            name="app",
            field=models.CharField(
                default=django.utils.timezone.now,
                help_text="Ushbu sektor qaysi tumanga(rayonga) tegishli ekanligini belgilang",
                max_length=255,
                verbose_name="Tuman(Rayon) nomi",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hosptal",
            name="gender",
            field=models.CharField(
                choices=[("yes", "Ha"), ("no", "Yo'q")],
                help_text="Ilg'or poliklinikami yo'qmi",
                max_length=255,
                verbose_name="Yetakchi poliklinikami",
            ),
        ),
    ]
