# Generated by Django 4.1.6 on 2023-04-04 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mahalla", "0014_sector_add_sector_app_alter_hosptal_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sector",
            options={
                "ordering": ["id"],
                "verbose_name": "Sektor",
                "verbose_name_plural": "Sektorlar",
            },
        ),
    ]
